### ISSUE TITLE
Add a “share link” button in territory page

### ISSUE THREAD

**Issue by rtercias** [rtercias/foreign-field#163]
Component: Territory

Add a “share link” button. When clicked, it should copy the url link to clipboard, and possibly open the device’s default text message app and paste it there.

This is necessary for the PWA app.

**Comment by rtercias** [comment]
https://stackoverflow.com/a/60915962

**Comment by benscriptstheweb** [comment]
oh thanks! this is a lot simpler than what i was hacking together.
