### ISSUE TITLE
add territory map view

### ISSUE THREAD

**Issue by rtercias** [rtercias/foreign-field#22]
In the single Territory view, add a toggle that switches between the current address list view and a map view.
Map view needs to be created using OpenStreetMaps (avoid Google as it is not free).

**Comment by rtercias** [comment]
Let's take a look at Leaflet also... might be easier to work with:
https://travishorn.com/interactive-maps-with-vue-leaflet-5430527353c8

**Comment by benscriptstheweb** [comment]
added the boiler plate for leaflet. do we want a route to a separate 'map page' or will the view be integrated with the address list in Territory.vue?

**Comment by rtercias** [comment]
good question. Let's add a route:

/territories/{:group}/{:id}/map
