### ISSUE TITLE
Confirmation box when adding territory shows the name of a different territory

### ISSUE THREAD

**Issue by KatrinaJewel** [rtercias/foreign-field#354]
When adding a new territory the confirmation box for saving the changes shows the name for a different territory not the name of the one being worked on.

**Comment by rtercias** [comment]
I don't see the name of the territory being displayed at all...
![image.png](https://images.zenhubusercontent.com/599b029e8f62dc7798c387b0/7050b321-79aa-4449-ae5f-6923b973cedf)

Can you clarify which confirmation box to investigate?

**Comment by KatrinaJewel** [comment]
It seems to only happen after any territory has been edited and then you add a new territory.
![Screenshot 2021-12-23 200626](https://user-images.githubusercontent.com/82837948/147303822-37b3ed9f-1c00-4959-ba83-018cd92c289e.png)

**Comment by rtercias** [comment]
ah, makes sense. I've fixed it. Please test in production.
