### ISSUE TITLE
S13 Formatting Issue

### ISSUE THREAD

**Issue by javalavajava** [rtercias/foreign-field#362]
![S13 error1](https://user-images.githubusercontent.com/22361563/147427716-a95b1093-3055-4bb4-bb0e-db702989ba38.png)
![S13 error2](https://user-images.githubusercontent.com/22361563/147427717-391e4e0a-3a2a-4378-913c-f0bacb8001cd.png)

There are formatting issues with the S13 report (see above).  This is in Stage.  
It doesn't matter what account to use as long as it can access S13.

**Comment by rtercias** [comment]
this is now fixed in production. I'm truncating the extra-long names so they don't overlap
