### ISSUE TITLE
Address Status in Phone Tab Doesn't Get Push

### ISSUE THREAD

**Issue by javalavajava** [rtercias/foreign-field#384]
This looks like just a low priority view-only problem since refreshing the page resolves it.

1. Go to a checked out territory page
2. Using another account, access the same checked out territory 
3. Enable 'Collaborate Mode' on both accounts
4. Add a new address to that territory
5. Using the account used in step 3, change the status of the address to 'Do Not Mail'
6. 'Do Not Mail' status does not get pushed to the other

**Comment by rtercias** [comment]
fixed
