### ISSUE TITLE
Address Removal Doesn't Fully Complete

### ISSUE THREAD

**Issue by javalavajava** [rtercias/foreign-field#385]
This is probably a low priority issue.  Just thought I'd log it in for reference.
Also, refreshing the page resolves it.

1. Go to a checked out territory page
2. Using another account, access the same checked out territory 
3. Enable 'Collaborate Mode' on both accounts
4. Add a new address to that territory
5. Using the account used in step 3, remove the address (3 dots on the left -> 'Remove')
6. Confirm address removal
7. The address remains and the loading icon is displayed but it never actually completes

**Comment by rtercias** [comment]
fixed
