### ISSUE TITLE
Show territories that a user has worked recently (not checked in to them)

### ISSUE THREAD

**Issue by rtercias** [rtercias/foreign-field#93]
Starting component: Welcome

Sometimes users share a territory link with one another. Currently, that link is only available to the recipient via text message. When a user visits a territory link that's not checked out to them, we can save that link into their local storage. 

Then, on the Welcome dashboard, we can display the links in a "Recently Visited" list.

"Recent" = 2 months long
Links older than 2 months can be dropped off the list.

**Comment by mingotek** [comment]
use localstorage
